order_management/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("userupdate/<int:user_id>", views.update_profile, name="update_profile"),
    path("removeuser/<int:user_id>", views.remove_user, name="remove_user"),
]

order_management/order_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

order_management/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.create_order, name="create-order"),
    path("list/", views.list_orders, name="order-list"),
    path("update/<int:order_id>", views.update_order, name="update-order"),
    path("remove/<int:order_id>", views.remove_order, name="remove-order"),
]

order_management/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class UserCreationFormCustom(UserCreationForm):
    username = forms.CharField(label="Username", min_length=5, max_length=150)
    email = forms.EmailField(label="E-Mail")
    first_name = forms.CharField(label="First Name", max_length=150)
    last_name = forms.CharField(label="Last Name", max_length=150, required=False)
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    def is_username_valid(self):
        username = self.cleaned_data["username"].lower()
        new = User.objects.filter(username=username)
        if new.count() > 0:
            raise ValidationError("The given username is taken")
        return username

    def is_email_valid(self):
        email = self.cleaned_data["email"].lower()
        new = User.objects.filter(email=email)
        if new.count() > 0:
            raise ValidationError("The given email is taken")
        return email

    def does_password2_match(self):
        pwd1 = self.cleaned_data["password1"]
        pwd2 = self.cleaned_data["password2"]

        if pwd1 and pwd2 and pwd1 != pwd2:
            raise ValidationError("Passwords do not match or are empty")

        return pwd2

    def are_names_valid(self):
        first_name = self.cleaned_data["first_name"]
        last_name = self.cleaned_data["last_name"]

        if not (first_name):
            raise ValidationError("Name fields cannot be empty")

        return first_name, last_name

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()

        return user


class UserUpdationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

order_management/accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, render, redirect
from .forms import UserCreationFormCustom, UserUpdationForm


def signup(request):
    if request.method == "POST":
        form = UserCreationFormCustom(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
        print(form.errors)
    else:
        form = UserCreationFormCustom()
    context = {"form": form}
    return render(request, "signup.html", context)


@login_required
def update_profile(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if user != request.user:
        return HttpResponseForbidden(
            "You cannot edit this user (Reason: Invalid credentials)"
        )

    if request.method == "POST":
        form = UserUpdationForm(
            request.POST,
            instance=user,
        )
        if form.is_valid():
            form.save()
            return redirect("home")
    else:
        form = UserUpdationForm(
            instance=user,
            initial={
                "First Name": user.first_name,
                "Last Name": user.last_name,
                "Email": user.email,
            },
        )
    context = {"form": form}
    return render(request, "update_user.html", context)


@login_required
def remove_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if user == request.user:
        user.delete()
    return redirect("home")

order_management/accounts/templates/update_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/list_orders.css' %}" rel="stylesheet">
        <title>Update Order</title>
    </head>
    <body style="background-color: #161616;">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                    </div>
                    <h2 class="text-center" style="color: #FFFFFF;">Update details</h2>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.first_name.id_for_label }}">First name:</label>
                            <input class="form-control"
                                   type="text"
                                   name="{{ form.first_name.name }}"
                                   value="{{ form.first_name.initial|default:'' }}"
                                   id="{{ form.first_name.id_for_label }}"
                                   required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.last_name.id_for_label }}">Last name:</label>
                            <input class="form-control"
                                   type="text"
                                   name="{{ form.last_name.name }}"
                                   value="{{ form.last_name.initial|default:'' }}"
                                   id="{{ form.last_name.id_for_label }}">
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.email.id_for_label }}">Email:</label>
                            <input class="form-control"
                                   type="text"
                                   name="{{ form.email.name }}"
                                   value="{{ form.email.initial|default:'' }}"
                                   id="{{ form.email.id_for_label }}"
                                   required>
                        </div>
                        <button class="btn btn-success btn-lg btn-block" type="submit">Save changes</button>
                    </form>
                    <br>
                    <div class="container mt-2">
                        <div class="row justify-content-center">
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'accounts:remove_user' user.id %}">
                                    <button class="btn btn-alert btn-block" type="submit">Delete Profile</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'home' %}">
                                    <button class="btn btn-primary btn-block home" type="submit">Return to homepage</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-block" type="submit">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">@ github.com/cross-codes</p>
    </body>
</html>