order_management/order_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

order_management/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.create_order, name="create-order"),
    path("list/", views.list_orders, name="order-list"),
    path("update/<int:order_id>", views.update_order, name="update-order"),
    path("remove/<int:order_id>", views.remove_order, name="remove-order"),
]

order_management/orders/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    PRIORITY_CHOICES = (("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.TextField()
    date = models.DateField()
    pr_tag = models.CharField(max_length=10, choices=PRIORITY_CHOICES, default="MEDIUM")

    def __str__(self):
        return self.title

order_management/orders/forms.py
from django import forms
from .models import Order


class UpdateOrder(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["title", "desc", "date", "pr_tag"]


class OrderSearchForm(forms.Form):
    search_query = forms.CharField(max_length=100, required=False)

order_management/orders/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from fuzzywuzzy import fuzz
from .models import Order
from .forms import UpdateOrder, OrderSearchForm


@login_required
def create_order(request):
    if request.method == "POST":
        title = request.POST["title"]
        desc = request.POST["desc"]
        date = request.POST["date"]
        pr_tag = request.POST["pr_tag"]
        order = Order(
            user=request.user, title=title, desc=desc, date=date, pr_tag=pr_tag
        )
        order.save()
        return redirect(reverse("orders:order-list"))
    return render(request, "create_order.html")


@login_required
def list_orders(request):
    orders = Order.objects.filter(user=request.user)
    search_form = OrderSearchForm(request.GET)
    fuzz_pratio_threshold = 75

    if search_form.is_valid():
        search_query = search_form.cleaned_data.get("search_query").lower()
        priority = request.GET.get("priority")
        if search_query:
            if priority in {"Low", "Medium", "High"}:
                orders = [
                    order
                    for order in orders
                    if order.pr_tag == priority.upper()
                    and fuzz.partial_ratio(search_query, order.title.lower())
                    >= fuzz_pratio_threshold
                ]
            else:
                orders = sorted(
                    [
                        order
                        for order in orders
                        if fuzz.partial_ratio(search_query, order.title.lower())
                        >= fuzz_pratio_threshold
                    ],
                    key=lambda order: {"LOW": 3, "MEDIUM": 2, "HIGH": 1}.get(
                        order.pr_tag, 1
                    ),
                )

            context = {
                "orders": orders,
                "search_form": search_form,
            }
            return render(
                request,
                "search_results.html",
                context,
            )
    return render(
        request,
        "list_orders.html",
        {"orders": Order.objects.filter(user=request.user), "search_form": search_form},
    )


@login_required
def remove_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if order.user == request.user:
        order.delete()
    return redirect("orders:order-list")


@login_required
def update_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)

    if order.user != request.user:
        return HttpResponseForbidden(
            "You cannot edit this order (Reason: Invalid Credentials)"
        )
    if request.method == "POST":
        form = UpdateOrder(
            request.POST,
            instance=order,
        )
        if form.is_valid():
            form.save()
            return redirect("orders:order-list")
    else:
        form = UpdateOrder(
            instance=order,
            initial={
                "title": order.title,
                "desc": order.desc,
                "date": order.date,
                "pr_tag": order.pr_tag,
            },
        )
    context = {"form": form}
    return render(request, "update_order.html", context)

order_management/orders/templates/create_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/list_orders.css' %}" rel="stylesheet">
        <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
        <title>Add Order</title>
    </head>
    <body style="background-color: #161616;">
        <div class="container mt-5" style="background-color: #161616;">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                    </div>
                    <h2 class="text-center" style="color: #FFFFFF;">Add an order</h2>
                    <form method="post" action="{% url 'orders:create-order' %}">
                        {% csrf_token %}
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="title">Title:</label>
                            <input class="form-control" type="text" id="title" name="title" required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="desc">Description:</label>
                            <input class="form-control" type="text" id="desc" name="desc" required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="date">Date:</label>
                            <input class="form-control" type="date" id="date" name="date" required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="pr_tag">Priority:</label>
                            <select class="form-control" id="pr_tag" name="pr_tag" required>
                                <option value="LOW">Low</option>
                                <option value="MEDIUM">Medium</option>
                                <option value="HIGH">High</option>
                            </select>
                        </div>
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Create Order</button>
                    </form>
                    <br>
                    <div class="container mt-2">
                        <div class="row justify-content-center">
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'home' %}">
                                    <button class="btn btn-secondary btn-block home" type="submit">Return to homepage</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-block" type="submit">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">@ github.com/cross-codes</p>
    </body>
</html>

order_management/orders/templates/list_orders.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/list_orders.css' %}" rel="stylesheet">
        <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
        <title>Your Orders</title>
    </head>
    <body style="background-color: #161616;">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                    </div>
                    <form method="get" action="{% url 'orders:order-list' %}">
                        <div class="row justify-content-center" style="color: #FFFFFF">
                            {{ search_form.as_p }}
                            <div class="col-4">
                                <select class="form-select" name="priority">
                                    <option value="" selected>Search by priority (Default: All)</option>
                                    <option value="Default">All matches (High -> Low)</option>
                                    <option value="Low">Low</option>
                                    <option value="Medium">Medium</option>
                                    <option value="High">High</option>
                                </select>
                            </div>
                            <div class="col-4 text-center">
                                <button class="btn btn-primary btn-sm" type="submit">Fuzzy Search</button>
                            </div>
                        </div>
                        <br>
                    </form>
                    <div class="container mt-2">
                        <div class="row justify-content-center">
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'orders:create-order' %}">
                                    <button class="btn btn-success" type="submit">Add order to the list</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'home' %}">
                                    <button class="btn btn-secondary btn-block home" type="submit">Return to homepage</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-block" type="submit">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <br>
                    <div class="card" style="background-color: #E7E7E7;">
                        <div class="card-body">
                            <h2 class="text-center">Your Orders</h2>
                            <ul class="list-unstyled">
                                {% for order in orders %}
                                    <li>
                                        <strong>Title:</strong> {{ order.title }}
                                        <br>
                                        <strong>Description:</strong> {{ order.desc }}
                                        <br>
                                        <strong>Date:</strong> {{ order.date }}
                                        <br>
                                        <strong>Priority Tag:</strong> {{ order.get_pr_tag_display }}
                                        <br>
                                        <div class="container mt-2">
                                            <div class="row justify-content-center">
                                                <div class="col-lg-4">
                                                    <form method="post" action="{% url 'orders:update-order' order.id %}">
                                                        {% csrf_token %}
                                                        <button class="btn btn-primary btn-block mb-2" type="submit">Update Order</button>
                                                    </form>
                                                </div>
                                                <div class="col-lg-4">
                                                    <form method="post" action="{% url 'orders:remove-order' order.id %}">
                                                        {% csrf_token %}
                                                        <button class="btn btn-danger btn-block mb-2" type="submit">Remove Order</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    <hr>
                                {% empty %}
                                    <p>You have no orders</p>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">@ github.com/cross-codes</p>
    </body>
</html>

order_management/orders/templates/search_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/list_orders.css' %}" rel="stylesheet">
        <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
        <title>Search Results</title>
    </head>
    <body style="background-color: #161616;">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                    </div>
                    <form method="get" action="{% url 'orders:order-list' %}">
                        <div class="row justify-content-center" style="color: #FFFFFF";>
                            {{ search_form.as_p }}
                            <div class="col-4">
                                <select class="form-select" name="priority">
                                    <option value="" selected>Search by priority (Default: All)</option>
                                    <option value="Default">All matches (High -> Low)</option>
                                    <option value="Low">Low</option>
                                    <option value="Medium">Medium</option>
                                    <option value="High">High</option>
                                </select>
                            </div>
                            <div class="col-4 text-center">
                                <button class="btn btn-primary btn-sm" type="submit">Fuzzy Search</button>
                            </div>
                        </div>
                        <br>
                    </form>
                    <div class="container mt-2">
                        <div class="row justify-content-center">
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'orders:order-list' %}">
                                    <button class="btn btn-primary btn-block" type="submit">Return to order-list</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-block" type="submit">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <br>
                    <h2 class="text-center" style="color: #FFFFFF;">Matching results</h2>
                    <ul class="list-unstyled">
                        {% for order in orders %}
                            <li>
                                <strong style="color: #FFFFFF;">Title:</strong> <span style="color: #FFFFFF;">{{ order.title }}</span>
                                <br>
                                <strong style="color: #FFFFFF;">Description:</strong> <span style="color: #FFFFFF;">{{ order.desc }}</span>
                                <br>
                                <strong style="color: #FFFFFF;">Date:</strong> <span style="color: #FFFFFF;">{{ order.date }}</span>
                                <br>
                                <strong style="color: #FFFFFF;">Priority Tag:</strong> <span style="color: #FFFFFF;">{{ order.get_pr_tag_display }}</span>
                                <br>
                                <div class="container mt-2">
                                    <div class="row justify-content-center">
                                        <div class="col-lg-4">
                                            <form method="post" action="{% url 'orders:update-order' order.id %}">
                                                {% csrf_token %}
                                                <button class="btn btn-primary btn-block mb-2" type="submit">Update Order</button>
                                            </form>
                                        </div>
                                        <div class="col-lg-4">
                                            <form method="post" action="{% url 'orders:remove-order' order.id %}">
                                                {% csrf_token %}
                                                <button class="btn btn-danger btn-block mb-2" type="submit">Remove Order</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <hr>
                        {% empty %}
                            <p style="color: #FFFFFF;">No matching orders found</p>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">@ github.com/cross-codes</p>
    </body>
</html>

order_management/orders/templates/update_order.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/list_orders.css' %}" rel="stylesheet">
        <title>Update Order</title>
    </head>
    <body style="background-color: #161616;">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="text-center">
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                    </div>
                    <h2 class="text-center" style="color: #FFFFFF;">Update order</h2>
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.title.id_for_label }}">Title:</label>
                            <input class="form-control"
                                   type="text"
                                   name="{{ form.title.name }}"
                                   value="{{ form.title.initial|default:'' }}"
                                   id="{{ form.title.id_for_label }}"
                                   required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.desc.id_for_label }}">Description:</label>
                            <input class="form-control"
                                   type="text"
                                   name="{{ form.desc.name }}"
                                   value="{{ form.desc.initial|default:'' }}"
                                   id="{{ form.desc.id_for_label }}"
                                   required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.date.id_for_label }}">Date:</label>
                            <input class="form-control"
                                   type="date"
                                   name="{{ form.date.name }}"
                                   value="{{ form.date.initial|default:'' }}"
                                   id="{{ form.date.id_for_label }}"
                                   required>
                        </div>
                        <div class="form-group" style="color: #FFFFFF;">
                            <label for="{{ form.pr_tag.id_for_label }}">Priority:</label>
                            <select class="form-control" id="pr_tag" name="pr_tag" required>
                                <option value="LOW">Low</option>
                                <option value="MEDIUM">Medium</option>
                                <option value="HIGH">High</option>
                            </select>
                        </div>
                        <button class="btn btn-success btn-lg btn-block" type="submit">Save changes</button>
                    </form>
                    <br>
                    <div class="container mt-2">
                        <div class="row justify-content-center">
                            <div class="col-lg-4">
                                <form method="get" action="{% url 'orders:order-list' %}">
                                    <button class="btn btn-primary btn-block" type="submit">Return to order list</button>
                                </form>
                            </div>
                            <div class="col-lg-4">
                                <form method="post" action="{% url 'logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-danger btn-block" type="submit">Logout</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted text-center">@ github.com/cross-codes</p>
    </body>
</html>