order_management/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("userupdate/<int:user_id>", views.update_profile, name="update_profile"),
    path("removeuser/<int:user_id>", views.remove_user, name="remove_user"),
]

order_management/order_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path("", include("orders.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

order_management/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    path("create/", views.create_order, name="create-order"),
    path("list/", views.list_orders, name="order-list"),
    path("update/<int:order_id>", views.update_order, name="update-order"),
    path("remove/<int:order_id>", views.remove_order, name="remove-order"),
]

order_management/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/home.css' %}" rel="stylesheet">
        <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
        <title>Home</title>
    </head>
    <body class="text-center" style="background-color: #161616;">
        <div class="card" style="background-color: #161616">
            <div class="card-body">
                <div class="col-md-4 mx-auto">
                    {% if user.is_authenticated %}
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <h2 class="text-center mb-4" style="color: #FFFFFF;">Welcome {{ user.first_name }}</h2>
                        {% load order_count %}
                        <div class="card" style="background-color: #E7E7E7;">
                            <div class="card-body">
                                <h3 class="card-title">
                                    <em>User Profile</em>
                                </h3>
                                <p>
                                    <strong>Username:</strong> {{ user.username }}
                                </p>
                                <p>
                                    <strong>First Name:</strong> {{ user.first_name }}
                                </p>
                                {% if user.last_name %}
                                    <p>
                                        <strong>Last Name:</strong> {{ user.last_name }}
                                    </p>
                                {% endif %}
                                <p>
                                    <strong>Email:</strong> {{ user.email }}
                                </p>
                                <p>
                                    <strong>Order Count:</strong> {% user_order_count user %}
                                </p>
                                <form method="get" action="{% url 'accounts:update_profile' user.id %}">
                                    {% csrf_token %}
                                    <button class="btn btn-primary btn-block btn-lg update_profile" type="submit">Update profile</button>
                                </form>
                            </div>
                        </div>
                        <br>
                        <form method="post" action="{% url 'orders:order-list' %}">
                            {% csrf_token %}
                            <button class="btn btn-primary btn-block btn-lg" type="submit">View Order List</button>
                        </form>
                        <br>
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="btn btn-danger btn-block btn-lg" type="submit">Log Out</button>
                        </form>
                    {% else %}
                        <img class="mb-4"
                             src="{% static 'img/banner.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <img class="mb-4"
                             src="{% static 'img/django.png' %}"
                             alt=""
                             width="72"
                             height="72">
                        <div class="card text-center">
                            <div class="card-body text-center">
                                <p>Welcome to the Order Management System</p>
                                <p>(GDSC - Round 2)</p>
                            </div>
                        </div>
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <button class="btn btn-primary btn-block btn-lg login" type="submit">Log In</button>
                        </form>
                        <br>
                        <form method="post" action="{% url 'accounts:signup' %}">
                            {% csrf_token %}
                            <button class="btn btn-success btn-block btn-lg signup" type="submit">Sign Up</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
        <p class="mt-5 mb-3 text-muted">@ github.com/cross-codes</p>
    </body>
</html>

order_management/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/signin.css' %}" rel="stylesheet">
        <link href="{% static 'css/signup.css' %}" rel="stylesheet">
        <link href="{% static 'css/buttons.css' %}" rel="stylesheet">
        <title>Sign Up</title>
    </head>
    <body style="background-color: #161616;">
        <div class="card" style="max-height: 800px; overflow-y: auto">
            <div class="card-body">
                <form class="form-signin text-center"
                      method="post"
                      action="{% url 'accounts:signup' %}">
                    <img class="mb-4"
                         src="{% static 'img/banner.png' %}"
                         alt=""
                         width="72"
                         height="72">
                    <img class="mb-4"
                         src="{% static 'img/django.png' %}"
                         alt=""
                         width="72"
                         height="72">
                    <h1 class="h3 mb-3 font-weight-normal card-title">Sign up</h1>
                    {% csrf_token %}
                    <div class="form-group">{{ form.as_p }}</div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
                    <br>
                    <p class="mt-5 mb-3 text-muted">@ github.com/cross-codes</p>
                </form>
            </div>
            <form method="get" action="{% url 'home' %}">
                <button class="btn btn-success btn-block btn-lg home" type="submit">Return Home</button>
            </form>
        </div>
    </body>
</html>